config/routes.rb
Rails.application.routes.draw do
  resources :menus do
    resources :docs do
      member do
        get :enhance_image_description
      end
    end
  end
  patch "/ai", to: "application#ai", as: "ai"
  root to: "home#index"
  get "home/index"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch "update_selection"
    end
  end
  resources :response_records do
    member do
      post "associate_response_image"
      post "remove_response_image"
    end
  end

  resources :images do
    post "find_or_create", on: :collection
    post "run_image_setup", on: :collection
    get "edit_multiple", on: :collection
    patch "update_multiple", on: :collection
    post "generate", on: :member
    get "crop", on: :member
    patch "croppable", on: :member
    post "purge_saved_images", on: :member
    post "describe", on: :member
  end
  resources :boards do
    member do
      patch "mark_as_favorite"
      patch "unfavorite"
      get "build"
      post "add_multiple_images"
      post "associate_image"
      post "remove_image"
      get "locked"
    end
  end
  resources :board_images do
    member do
      get "next"
      get "previous"
      patch "click"
    end
  end

  resources :response_boards, only: [:index, :show] do
    member do
      post "associate_response_image"
      post "remove_response_image"
    end
  end

  resources :response_images do
    member do
      get "next"
      get "previous"
      patch "click"
    end
  end

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/doc.rb
# == Schema Information
#
# Table name: docs
#
#  id                :bigint           not null, primary key
#  documentable_type :string           not null
#  image_description :text
#  name              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  documentable_id   :bigint           not null
#
# Indexes
#
#  index_docs_on_documentable  (documentable_type,documentable_id)
#
class Doc < ApplicationRecord
  belongs_to :documentable, polymorphic: true
  has_one_attached :image
  has_many :boards
  # has_one :board
  has_many :images, through: :boards

  include ImageHelper

  # before_create :save_raw_text
  after_create :enhance_image_description

  def current_board
    boards.last
  end

  def save_raw_text
    self.raw_text = self.image_description
  end

  def image_name
    name.blank? ? documentable.name : name
  end

  def create_board_from_image
    board = Board.new
    board.doc = self
    board.name = self.name || "Board for Doc #{id}"
    board.save!
    create_images_from_description(board)
    board
  end

  def create_images_from_description(board)
    puts "**** create_images_from_description **** \n"
    json_description = JSON.parse(image_description)
    json_description["food"].each do |food|
      puts "food: #{food}\n"
      item_name = menu_item_name(food["name"])
      puts "Finding or creating image for #{item_name}\n"
      image = Image.find_or_create_by!(label: item_name)
      image.label = item_name
      unless food["image_description"].blank?
        image.image_prompt = food["image_description"]
      else
        image.image_prompt = "Create an image of #{item_name}"
        image.image_prompt += " with #{food["description"]}" if food["description"]
      end
      puts "\n\n\n***image.image_prompt: #{image.image_prompt}\n"
      # image.send_request_on_save = true
      # image.private = false
      image.save!
      board.add_image(image.id)
      image.start_generate_image_job unless image.display_image.attached?
    end
  end

  def menu_item_name(item_name)
    item_name.downcase!
    # Strip out any non-alphanumeric characters
    item_name.gsub(/[^a-z ]/i, '')
    puts "item_name: #{item_name}\n"
    item_name
  end



  def enhance_image_description
    # return unless image_description
    puts "Image description before: #{image_description}\n raw_text: #{raw_text}\n"

    if !raw_text.blank?
      self.image_description = clarify_image_description
      puts "Image description after: #{image_description}\n"
      puts "**** ERROR **** \nNo image description provided.\n" unless image_description
      self.save!
      create_board_from_image
    else
      puts "Image description invaild: #{image_description}\n"
      image_description
    end
  end

  def external_image_url
    self.image.representation(resize_to_limit: [100, 100]).processed.url
  end

  def proxy_image_url
    rails_storage_proxy_path(image)
  end

  def main_image_on_disk
    throw "No image attached to Doc #{id}" unless image.attached?
    external_image_url
  end

  def image_path
    image_path = image.attached? ? Rails.application.routes.url_helpers.rails_blob_path(image, only_path: true) : nil
    puts "image_path: #{image_path}"
    image_path
  end

  def open_ai_opts
    { prompt: prompt_to_send }
  end

  def prompt_to_send
    description_prompt
  end

  def description_prompt
    "Please describe the food and drink options on this kid's restaurant menu."
  end
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: %i[ show edit update destroy ]

  # GET /docs or /docs.json
  def index
    @menu = Menu.find(params[:menu_id]) if params[:menu_id]
    @docs = @menu.docs
  end

  # GET /docs/1 or /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @menu = Menu.find(params[:menu_id]) if params[:menu_id]
    @doc = Doc.new
    @doc.documentable = @menu
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs or /docs.json
  def create
    @doc = Doc.new(doc_params)
    @menu = Menu.find(params[:menu_id]) if params[:menu_id]
    @doc.name = @menu.name + " - " + @doc.id.to_s
    @doc.documentable = @menu

    respond_to do |format|
      if @doc.save
        @current_board = @doc.current_board
        format.html { redirect_to menu_url(@menu), notice: "Doc was successfully created." }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def enhance_image_description
    @doc = Doc.find(params[:id])
    @menu = Menu.find(params[:menu_id]) if params[:menu_id]
    # @doc.get_image_description
    @doc.enhance_image_description
    respond_to do |format|
      format.html { redirect_to menu_doc_url(@menu, @doc), notice: "Image description was successfully created." }
      format.json { render :show, status: :created, location: @doc }
    end
  end

  # PATCH/PUT /docs/1 or /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to menu_doc_url(@menu, @doc), notice: "Doc was successfully updated." }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1 or /docs/1.json
  def destroy
    @doc.destroy!

    respond_to do |format|
      format.html { redirect_to menu_docs_url(@menu), notice: "Doc was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @menu = Menu.find(params[:menu_id]) if params[:menu_id]
      @doc = Doc.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doc_params
      params.require(:doc).permit(:name, :documentable_id, :documentable_type, :image, :image_description, :raw_text)
    end
end

app/helpers/docs_helper.rb
module DocsHelper
    def image_for_doc(doc)
        str = ""
        if !doc.image.attached?
          str += "<div class='h-52 w-52 text-gray-400 text-2xl font-bold grid justify-items-center items-center shadow mx-auto my-auto'><span class='mx-auto my-auto'>#{doc.name.upcase}</span></div>".html_safe
        else
          str += image_tag(doc.image.representation(resize_to_limit: [500, 500]).processed.url, class: "shadow mx-auto my-auto")
        end
        str.html_safe
    end
end

app/views/docs/_current_board.html.erb
<div class="mx-auto w-full p-4" data-controller="static-board">
  <div class="text-center">
    <ul class="flex justify-center text-4xl font-bold" id="the-list" data-static-board-target="list"></ul>

    <div class="mx-auto w-1/2 p-4 flex justify-around">
      <button class="bg-gray-100 rounded-lg py-3 px-5 font-medium" data-action="click->static-board#clearList">Clear</button>
      <button class="bg-green-100 rounded-lg py-3 px-5 font-medium" data-action="click->static-board#speakList">Speak</button>
    </div>

  </div>
  <h2 class="text-2xl font-bold mb-4"><%= board.name %> <%= user_board_info(board) %></h2>
  <h3 class="text-xl font-medium mb-4"><%= board.board_images.count %> total images</h3>
  <div class="p3 flex justify-evenly mb-5">
    <%= link_to "Edit", edit_board_path(board), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
        <%= link_to "PLAY MODE", locked_board_path(board), class: "mt-2 px-4 py-2 rounded-lg bg-orange-600 text-white text-3xl font-medium hover:bg-orange-700" %>

      <%= link_to "Add more images", build_board_path(board), class: "rounded-lg py-3 px-5 bg-gray-100 font-medium" %>

    <% unless board.static %>
    <h3>Next Board: <%= board.next_board ? link_to(board.next_board.name, board.next_board) : "None" %> </h3>
    <% end %>
  </div>
    

    <div class="flex justify-center">
      <div class="p-3 m-2 border w-3/4">
        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
          <%= render board.board_images %>
        </div>
      </div>
    </div>

  <div class="mt-6 flex justify-end space-x-2">
    <%= button_to "Destroy", board_path(board), method: :delete, class: "rounded-lg py-3 px-5 bg-red-600 text-white font-medium", form_class: "" %>
  </div>
</div>

app/views/docs/_doc.html.erb
<div id="<%= dom_id doc %>">
  <p>
    <strong>Name:</strong>
    <%= doc.name %>
  </p>

  <p>
    <strong>Documentable:</strong>
    <%= doc.documentable_id %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= link_to doc.image.filename, doc.image if doc.image.attached? %>
  </p>

</div>

app/views/docs/_form.html.erb
<%= form_with(model: [@menu, doc], local: true, data: { controller: "ocr disable" }) do |form| %>
  <% if doc.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
        <% doc.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.text_field :raw_text, data: { ocr_target: "image_description" }, class: "h-32 w-3/4 border-2" %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image, data: { ocr_target: "file", action: "change->ocr#upload" } %>
  </div>

  <div>
        <%= form.submit "Save", class: "text-white shadow rounded-lg py-2 px-4 bg-green-700 font-medium text-center", data: { ocr_target: "submit_button", disable_target: "button", action: "click->disable#disableForm" } %>

  </div>
<% end %>

app/views/docs/edit.html.erb
<h1>Editing doc</h1>

<%= render "form", doc: @doc %>

<br>

<div>
  <%= link_to "Show this doc", menu_doc_path(@menu, @doc) %> |
  <%= link_to "Back to docs", menu_docs_path %>
</div>

app/views/docs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Docs</h1>

<div id="docs">
  <% @docs.each do |doc| %>
    <%= render doc %>
    <p>
      <%= link_to "Show this doc", menu_doc_path(@menu, doc) %>
    </p>
  <% end %>
</div>

<%= link_to "New doc", new_menu_doc_path %>

app/views/docs/new.html.erb
<h1>New doc</h1>

<%= render "form", doc: @doc %>

<br>

<div>
  <%= link_to "Back to docs", menu_docs_path %>
</div>

app/views/docs/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="my-5">
  <p>
    <strong>Name:</strong>
    <%= @doc.name %>
  </p>
</div>

<%= link_to "Current Board", board_path(@doc.current_board) %>

<div class="flex justify-around">
  <%= image_tag @doc.image, class: "w-1/4" if @doc.image.attached? %>
  <div class="flex flex-wrap">
    <%= render "current_board", board: @doc.current_board %>
  </div>
</div>
<div class="my-5">
  <p class="text-2xl">image_description: <%= @doc.image_description %></p>
  <p class="text-xs">raw_text: <%= @doc.raw_text %></p> 
</div>

<div>
  <%= link_to "Edit this doc", edit_menu_doc_path(@menu, @doc) %> |
  <%= link_to "Back to docs", menu_docs_path(@menu) %>

  <%= link_to "Get Image Description", enhance_image_description_menu_doc_path(@menu, @doc), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>

  <%= button_to "Destroy this doc", menu_doc_path(@menu, @doc), method: :delete %>
</div>