config/routes.rb
Rails.application.routes.draw do
  resources :menus do
    resources :docs do
      member do
        get :enhance_image_description
      end
    end
  end
  patch "/ai", to: "application#ai", as: "ai"
  root to: "home#index"
  get "home/index"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch "update_selection"
    end
  end
  resources :response_records do
    member do
      post "associate_response_image"
      post "remove_response_image"
    end
  end

  resources :images do
    post "find_or_create", on: :collection
    post "run_image_setup", on: :collection
    get "edit_multiple", on: :collection
    patch "update_multiple", on: :collection
    post "generate", on: :member
    get "crop", on: :member
    patch "croppable", on: :member
    post "purge_saved_images", on: :member
    post "describe", on: :member
  end
  resources :boards do
    member do
      patch "mark_as_favorite"
      patch "unfavorite"
      get "build"
      post "add_multiple_images"
      post "associate_image"
      post "remove_image"
      get "locked"
    end
  end
  resources :board_images do
    member do
      get "next"
      get "previous"
      patch "click"
    end
  end

  resources :response_boards, only: [:index, :show] do
    member do
      post "associate_response_image"
      post "remove_response_image"
    end
  end

  resources :response_images do
    member do
      get "next"
      get "previous"
      patch "click"
    end
  end

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/doc.rb
# == Schema Information
#
# Table name: docs
#
#  id                :bigint           not null, primary key
#  documentable_type :string           not null
#  image_description :text
#  name              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  documentable_id   :bigint           not null
#
# Indexes
#
#  index_docs_on_documentable  (documentable_type,documentable_id)
#
class Doc < ApplicationRecord
  belongs_to :documentable, polymorphic: true
  has_one_attached :image
  has_many :boards
  # has_one :board
  has_many :images, through: :boards

  include ImageHelper

  # before_create :save_raw_text
  after_create :enhance_image_description

  def current_board
    boards.last
  end

  def save_raw_text
    self.raw_text = self.image_description
  end

  def image_name
    name.blank? ? documentable.name : name
  end

  def create_board_from_image
    board = Board.new
    board.doc = self
    board.name = self.name || "Board for Doc #{id}"
    board.save!
    create_images_from_description(board)
    board
  end

  def create_images_from_description(board)
    puts "**** create_images_from_description **** \n"
    json_description = JSON.parse(image_description)
    json_description["food"].each do |food|
      puts "food: #{food}\n"
      item_name = menu_item_name(food["name"])
      puts "Finding or creating image for #{item_name}\n"
      image = Image.find_or_create_by!(label: item_name)
      image.label = item_name
      unless food["image_description"].blank?
        image.image_prompt = food["image_description"]
      else
        image.image_prompt = "Create an image of #{item_name}"
        image.image_prompt += " with #{food["description"]}" if food["description"]
      end
      puts "\n\n\n***image.image_prompt: #{image.image_prompt}\n"
      # image.send_request_on_save = true
      # image.private = false
      image.save!
      board.add_image(image.id)
      image.start_generate_image_job unless image.display_image.attached?
    end
  end

  def menu_item_name(item_name)
    item_name.downcase!
    # Strip out any non-alphanumeric characters
    item_name.gsub(/[^a-z ]/i, '')
    puts "item_name: #{item_name}\n"
    item_name
  end



  def enhance_image_description
    # return unless image_description
    puts "Image description before: #{image_description}\n raw_text: #{raw_text}\n"

    if !raw_text.blank?
      self.image_description = clarify_image_description
      puts "Image description after: #{image_description}\n"
      puts "**** ERROR **** \nNo image description provided.\n" unless image_description
      self.save!
      create_board_from_image
    else
      puts "Image description invaild: #{image_description}\n"
      image_description
    end
  end

  def external_image_url
    self.image.representation(resize_to_limit: [100, 100]).processed.url
  end

  def proxy_image_url
    rails_storage_proxy_path(image)
  end

  def main_image_on_disk
    throw "No image attached to Doc #{id}" unless image.attached?
    external_image_url
  end

  def image_path
    image_path = image.attached? ? Rails.application.routes.url_helpers.rails_blob_path(image, only_path: true) : nil
    puts "image_path: #{image_path}"
    image_path
  end

  def open_ai_opts
    { prompt: prompt_to_send }
  end

  def prompt_to_send
    description_prompt
  end

  def description_prompt
    "Please describe the food and drink options on this kid's restaurant menu."
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, :set_current_user
  before_action :set_image, only: %i[ show edit update destroy speak generate crop croppable ]

  # GET /images or /images.json
  def index
    if params[:user_images_only] == "1"
      @images = current_user.images.includes(cropped_image_attachment: :blob, saved_image_attachment: :blob).page params[:page]
    else
      @images = Image.includes(cropped_image_attachment: :blob, saved_image_attachment: :blob).searchable_images_for(current_user).order(created_at: :desc).page params[:page]
    end
    if params[:query].present?
      @images = @images.searchable_images_for(current_user).where("label ILIKE ?", "%#{params[:query]}%").order(updated_at: :desc).page params[:page]
    else
      @images = @images.searchable_images_for(current_user).order(updated_at: :desc).page params[:page]
    end
    if turbo_frame_request?
      render partial: "images", locals: { images: @images }
    else
      render :index
    end
  end

  def edit_multiple
    @images = Image.all.order(label: :asc)
  end

  def update_multiple
    puts "update_multiple: #{params}"
    image_ids = params[:image_ids]
    if params[:commit] == "Delete"
      Image.destroy(image_ids)
      redirect_to edit_multiple_images_url, notice: "Images were successfully deleted."
    elsif params[:commit] == "Generate"
      if image_ids.count > 5
        redirect_to edit_multiple_images_url, notice: "You can only generate 5 images at a time."
        return
      end
      image_ids.each do |image_id|
        GenerateImageJob.perform_async(image_id)
      end
      redirect_to edit_multiple_images_url, notice: "Images are generating."
    elsif params[:commit] == "Add to Board"
      image_ids.each do |image_id|
        BoardImage.create(board_id: params[:board_id], image_id: image_id)
      end
      redirect_to board_path(params[:board_id]), notice: "Images were successfully added to board."
    else
      redirect_to edit_multiple_images_url, notice: "Images were not updated. Unknown action. #{params[:commit]}"
    end
  end

  def run_image_setup
    ImageSetupJob.perform_async if current_user.admin?
    redirect_to images_url, notice: "Image setup is running."
  end

  def find_or_create
    @image = Image.searchable_images_for(current_user).find_by(label: params[:label], private: false)
    @found_image = @image
    @image = Image.create(label: params[:label], private: false) unless @image
    if @found_image
      notice = "Image found!"
    else
      notice = "New image created!"
    end
    if @ai_enabled
      @image.generate_image
      notice += " Image is generating."
      redirect_to image_url(@image), notice: notice
    else
      redirect_to image_url(@image), notice: notice
    end
  end

  def generate
    GenerateImageJob.perform_async(@image.id)
    Rails.logger.info "Generate Image: #{@image.label}"
    redirect_to images_url, notice: "Your image is generating."
  end

  # GET /images/1 or /images/1.json
  def show
    puts "SHOW\n\nr@image.display_image: #{image_url(@image.display_image)}"
  end

  def describe
    @image = Image.find(params[:id])
    image_url = @image.saved_image.attached? ? rails_storage_proxy_path(@image.saved_image) : ""
    puts "describe from controller - not used: #{image_url}"
    puts "image_url(@image): #{image_url(@image)}"
    @image.generate_description
    redirect_to image_url(@image), notice: "Image description is generating."
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
    if @image.user != current_user && !current_user.admin?
      redirect_to images_url, notice: "You can only edit your own images."
      # elsif @image.saved_image.attached? && !@image.cropped_image.attached?
      #   redirect_to crop_image_url(@image), notice: "You must crop your image before continuing."
    end
  end

  # POST /images or /images.json
  def create
    @image = Image.new(image_params)
    @image.user = current_user

    respond_to do |format|
      if @image.save
        format.html { redirect_to images_url }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to image_url(@image), notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def crop
    @image_url = @image.saved_image.attached? ? rails_storage_proxy_path(@image.saved_image) : ""
    @cropped_image_url = @image.cropped_image.attached? ? rails_storage_proxy_path(@image.cropped_image) : ""
  end

  def croppable
    @image.cropped_image.attach(
      io: StringIO.new(Base64.decode64(image_params[:cropped_image])),
      filename: "cropped_image_#{@image.id}.jpg",
      content_type: "image/x-bmp",
    )
    if @image.cropped_image.attached?
      @image.saved_image.purge
    end
    render json: { status: "success", redirect_url: images_url, notice: "Image was successfully cropped & saved." }
  end

  def purge_saved_images
    @image = Image.find(params[:id])
    @image.saved_image.purge
    @image.cropped_image.purge
    redirect_to image_url(@image), notice: "Image was successfully purged."
  end

  # DELETE /images/1 or /images/1.json
  def destroy
    @image.destroy

    respond_to do |format|
      format.html { redirect_to images_url, notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
    puts "set_image: #{@image}"
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:image_url, :audio_url, :label, :send_request_on_save, :saved_image, :image_prompt, :private, :cropped_image, :category)
  end
end

app/helpers/images_helper.rb
module ImagesHelper
  def generate_image_button(image)
    button_to "#{icon("fa-regular", "image")} CREATE Image".html_safe, generate_image_path(image), class: "rounded-full", method: :post
  end

  def remove_image_button(board, image)
    button_to "#{icon("fa-solid", "trash")}".html_safe, remove_image_board_path(board, image_id: image.id), class: "text-red-600 hover:text-red-700 py-1 px-1 rounded-full absolute bottom-0 left-0", method: :post
  end

  def purge_saved_images_button(image)
    button_to "#{icon("fa-solid", "trash")} Delete Image".html_safe, purge_saved_images_image_path(image.id), class: "text-red-600 hover:text-red-700 py-1 px-1 rounded-full", method: :post
  end

  def describe_image_button(image)
    button_to "#{icon("fa-regular", "comment-dots")} Describe Image".html_safe, describe_image_path(image), class: "rounded-full", method: :post
  end

  def speech_button(image)
    button_to icon("fa-regular", "comment-dots"), speak_image_path(image), class: "btn", method: :post
  end

  def saved_image_link(image)
    unless image.cropped_image.attached? || image.saved_image.attached?
      str = "<div class='absolute top-0 left-0 w-full h-full bg-gray-200 flex items-center justify-center text-gray-400 text-2xl font-bold' data-action='click->speech#speak'>#{image.label.upcase}</div>"
      return str.html_safe
    end
    image_tag(image.display_image.representation(resize_to_limit: [100, 100]).processed.url, data: { action: "click->speech#speak" })
  end

  # def select_image_button(board, image, size: "thumnail")
  #   unless image.display_image.attached?
  #     puts "no image"
  #     str = "<div class='absolute top-0 left-0 w-full h-full bg-gray-200 flex items-center justify-center text-gray-400 text-2xl font-bold'>#{image.label.upcase}</div>"
  #     return button_to(associate_image_board_path(board, image_id: image), data: { turbo: false }, class: "relative w-full h-0 pb-[100%]") do
  #              str.html_safe
  #            end
  #     # return button_to(image.label, associate_image_board_path(board, image_id: image), data: { turbo: false })
  #   end
  #   button_to(associate_image_board_path(board, image_id: image), data: { turbo: false }, class: "relative w-full h-0 pb-[100%]") do
  #     image_tag(image.display_image.representation(resize_to_limit: [200, 200]).processed.url)
  #   end
  # end
end

app/views/images/_board_image.html.erb
<div id="<%= dom_id image %>" class="w-full">
  <div class="bg-white rounded-lg shadow overflow-hidden group">
    <div class="relative w-full h-0 pb-[100%]"> <!-- Aspect Ratio Box -->
      <%= remove_image_button(@board, image) %>
      <% if image.private %>
        <span class="absolute top-2 right-2 bg-gray-900 bg-opacity-75 text-white text-xs px-1.5 py-0.5 rounded-full">Private</span>
      <% end %>
    </div>
    <div class="p-4">
      <p class="truncate text-gray-800 font-medium">
        <%= image.label %>
      </p>
    </div>
  </div>
</div>

app/views/images/_cropped_image.html.erb
  <% image_url = image.saved_image.attached? ? rails_storage_proxy_path(image.saved_image) : "" %>
  <% cropped_image_url = image.cropped_image.attached? ? rails_storage_proxy_path(image.cropped_image) : "" %>

  <%= content_tag(:div, "", data: {
                              controller: "images",
                              images_url: image_url,
                              images_id: image.id,
                            }, class: "w-full justify-between items-center") do %>
    <div class="w-full border">
      <%= image_tag(image_url, class: "w-full", id: "source", data: {
                                 images_target: "source",
                               }) %>
      <%= button_to "Crop", "#", data: {
                                   action: "click->images#click",
                                   images_target: "cropButton",
                                 }, method: :get %>
    </div>
    <div class="w-full">
      <%= image_tag(cropped_image_url, class: "", id: "output", data: {
                                         images_target: "output",
                                       }) %>
    </div>
  <% end %>

app/views/images/_find_or_create.html.erb
<%= form_with(url: find_or_create_images_path, method: :post, class: "m-5") do |form| %>
<div class="flex space-x-3">
    <%= form.text_field :label, placeholder: "Find or Create an Image", class: "mr-2 w-2/3 sm:w-1/2 py-2 px-3 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none" %>
    <%= form.submit "GO", class: "mx-auto px-3 py-2 font-medium bg-green-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-green-400 focus:ring-4 ring-0 focus:ring-green-100 mr-3" %>
</div>
<% end %>

app/views/images/_form.html.erb
<%= form_with(model: image, class: "contents mb-8", id: "new_image_form", data: { controller: "disable" }) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :category %>
    <%= form.select :category,
                    options_for_select(Image.category_options.sort, selected: form.object.category),
                    {}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :label %>
    <%= form.text_field :label, placeholder: "What should I say?", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :private %>
    <%= form.check_box :private, class: "shadow rounded-md border border-gray-200 outline-none px-4 py-2 mt-2 ml-3 inline" %>
  </div>

  <div class="my-5">
      <%= form.file_field :saved_image, data: { upload_target: "input" }, class: "rounded-md outline-none px-3 py-2 mt-2 w-1/2" %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "text-white shadow rounded-lg py-2 px-4 bg-green-700 font-medium text-center", data: { disable_target: "button", action: "click->disable#disableForm" } %>
    <% if image.persisted? %>
    <%= link_to "Crop", crop_image_path(@image), class: "text-white shadow rounded-lg py-2 px-4 bg-cyan-700 font-medium text-center" %>
    <% end %>
  </div>
<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>" class="inline-block mr-4 w-16 md:w-32 lg:w-48">
    <p class="m-2 truncate">
    <%= link_to image.label, edit_image_path(image), class: "rounded-lg inline-block font-medium", data: { turbo: false } %>   <%= icon("fa-solid", "lock") if image.private %>
    </p>
    <%= image_tag image.display_image, class: "w-full" if image.display_image.attached? %>
</div>

app/views/images/_images.html.erb
<%= turbo_frame_tag "image_list" do %>
  <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
    <% images.each do |image| %>
      <div id="<%= dom_id image %>" class="w-full">
        <div class="bg-white rounded-lg shadow overflow-hidden group">
          <div class="relative w-full h-0 pb-[100%]"> <!-- Aspect Ratio Box -->
            <% if image.display_image.attached? %>
              <%= image_tag image.display_image, class: "absolute top-0 left-0 w-full h-full object-contain", data: { action: "click->speech#speak" } %>
            <% else %>
              <div class="absolute top-0 left-0 w-full h-full bg-gray-200 flex items-center justify-center text-gray-400 text-2xl font-bold" data-action="click->speech#speak"><%= image.label.upcase %></div>
            <% end %>
            <% if image.private %>
              <span class="absolute top-2 right-2 bg-gray-900 bg-opacity-75 text-white text-xs px-1.5 py-0.5 rounded-full">Private</span>
            <% end %>
          </div>
          <div class="p-4">
            <p class="truncate text-gray-800 font-medium hover:text-blue-600">
              <%= link_to image.label, image_path(image), class: "rounded-lg", data: { turbo: false } %>
            </p>
            <p class="text-gray-600 text-xs"><%= time_ago_in_words(image.created_at) %> ago</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/images/_search.html.erb
<%= form_with(url: images_path, method: :get, data: { controller: "search-form", turbo_frame: "images", turbo_action: "advance", search_form_useronly_value: params["user_images_only"], search_form_query_value: params["query"] }) do |form| %>
  <div class="flex flex-wrap items-center justify-between gap-4 w-full md:w-3/4 xl:w-1/2 mb-4">
    <%= form.text_field :query, placeholder: "Search images...", class: "flex-grow py-2 px-4 rounded border-2 border-gray-300 focus:border-blue-500 focus:ring focus:ring-blue-200 transition duration-150 ease-in-out w-full md:w-auto", data: { search_form_target: "query", action: "input->search-form#search" } %>
    <%= form.submit "Search", class: "shrink-0 px-4 py-2 font-medium bg-blue-500 text-white rounded hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-300" %>
    <%= link_to "Clear", images_path, class: "shrink-0 px-4 py-2 font-medium bg-gray-200 text-gray-700 rounded hover:bg-gray-300 focus:outline-none focus:ring-2 focus:ring-gray-300" %>
    
    <div class="flex items-center space-x-2 justify-end">
      <%= form.check_box :user_images_only, class: "form-checkbox h-5 w-5 text-blue-600 rounded focus:ring-blue-500", data: { search_form_target: "userImagesOnly", action: "input->search-form#search" } %>
      <%= form.label :user_images_only, "Only my images", class: "text-sm font-medium text-gray-700" %>
    </div>
  </div>
<% end %>

app/views/images/_upload.html.erb
<% # NOT_IN_USE - See app/javascript/controllers/upload_controller.js %>
<% image_url = image.saved_image.attached? ? rails_storage_proxy_path(image.saved_image) : "" %>

<% cropped_image_url = image.cropped_image.attached? ? rails_storage_proxy_path(image.cropped_image) : "" %>

<%= content_tag(:div, "", class: "", data: {
                            controller: "upload",
                          }) do %>
    <div class="my-5">
        <%= form.label :upload %>
        <%= form.file_field :saved_image, data: { upload_target: "input" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>

    </div>
    <div class="w-full">
        <%= image_tag image_url, class: "", id: "preview", data: {
                                   upload_target: "preview",
                                 } %>
    </div>
    <div class="my-5">
    <%= link_to "Crop", "#", data: {
                               action: "click->upload#click",
                               upload_target: "cropButton",
                             }, method: :get %>
    </div>
    <div class="w-full">
      <%= image_tag(cropped_image_url, class: "image", id: "output", data: {
                                         upload_target: "output",
                                       }) %>
    </div>
  <% end %>

app/views/images/edit.html.erb
<div class="shadow mt-8 p-2 border">
  <div class="m-5">
    <h1 class="font-bold text-4xl">Editing image</h1>
    <p class="font-light text-gray-500"><%= @image.label %></p>
    <%= render "form", image: @image %>
  </div>
  <div class="">
        <%= link_to "Show", image_path(@image), class: "text-white  mt-2 shadow rounded-lg py-2 px-4 bg-blue-700 font-medium text-center" %>

    <%= button_to "Destroy", image_path(@image), method: :delete, class: "text-white  mt-2 shadow rounded-lg py-2 px-4 bg-red-700 font-medium text-center", form_class: "" %>
</div>

app/views/images/edit_multiple.html.erb
<div data-controller="checkbox-select-all">
  <div class="p-3 border rounded flex justify-between items-center">
    <p class="text-xl text-gray-600"> Selected: <span data-checkbox-select-all-target="count">0</span></p>
    <%= button_to "Run Image Setup Job", run_image_setup_images_path, method: :post, data: { turbo_confirm: "Are you sure you want to run this job?" }, class: "bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 border border-blue-600 rounded shadow" %>
  </div>
  <%= form_with url: update_multiple_images_path, method: :patch, id: :bulk_actions_form do |form| %>
    <%= form.submit "Delete", data: { turbo_confirm: "Are you sure you want to delete these images?" }, class: "bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded shadow" %>
    <%= form.submit "Generate", data: { turbo_confirm: "Are you sure you want to generate these images?" }, class: "bg-green-500 hover:bg-green-600 text-white font-semibold py-2 px-4 border border-green-600 rounded shadow" %> 
  <% end %>
  <div class="flex justify-around">
    <div class="border p-3 w-1/3">
      <div class="mx-auto w-1/4 p-3 border rounded flex justify-between items-center m-3">
        <%= label_tag "select all" %>
        <%= check_box_tag "select all", nil, nil, { data: { checkbox_select_all_target: "parent1", action: "change->checkbox-select-all#toggleChildren1" } } %>
      </div>
      <h3 class="text-xl text-gray-600 text-center m-2">Images without saved attachments</h3>
      <ul data-checkbox-select-all-target="children">
        <% @images.without_attached_saved_image.each do |image| %>
          <li class="flex justify-between border pl-3 pr-3 items-center">
            <%= link_to image.label, image_path(image), class: "text-blue-500 hover:text-blue-600" %>
            <%= check_box_tag "image_ids[]", image.id, nil, { data: { checkbox_select_all_target: "child1", action: "change->checkbox-select-all#toggleParent1" }, multiple: true, form: :bulk_actions_form } %>
          </li>
        <% end %>
      </ul>
    </div>


    <div class="border p-3 w-1/3">
      <div class="mx-auto w-1/4 p-3 border rounded flex justify-between items-center m-3">
        <%= label_tag "select all" %>
        <%= check_box_tag "select all", nil, nil, { data: { checkbox_select_all_target: "parent2", action: "change->checkbox-select-all#toggleChildren2" } } %>
      </div>
      <h3 class="text-xl text-gray-600 text-center m-2">Images with attachments</h3>
      <ul data-checkbox-select-all-target="children">
        <% @images.with_attached_saved_image.each do |image| %>
          <li class="flex justify-between border pl-3 pr-3 items-center">
            <%= link_to image.label, image_path(image), class: "text-blue-500 hover:text-blue-600" %>
            <%= check_box_tag "image_ids[]", image.id, nil, { data: { checkbox_select_all_target: "child2", action: "change->checkbox-select-all#toggleParent2" }, multiple: true, form: :bulk_actions_form } %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/images/index.html.erb
<div class="mx-auto w-full px-4 sm:px-6 lg:px-8">
  <% if current_user.admin? %>
  <%= link_to "Edit Multiple", edit_multiple_images_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-semibold py-2 px-4 border border-blue-600 rounded shadow" %>
    <p class="text-xs text-gray-400">Generating AI Images: <%= ResponseBoard::CREATE_AI_IMAGES %> </p>
    <% end %>
      <div class="flex justify-between items-center mb-10">

    <h1 class="font-bold text-4xl text-gray-800">Image Library </h1>

    <%= link_to "New image", new_image_path, class: "bg-green-500 hover:bg-green-600 text-white font-semibold py-2 px-4 border border-green-600 rounded shadow" %>
  </div>
  <%= render "utils/search", search_path: images_path, show_user_images_only: true %>

  <div class="mt-4 overflow-hidden">
        <%= paginate @images %>

    <%= render "images", images: @images %>
  </div>

</div>

app/views/images/show.html.erb
<div class="mx-auto px-4 sm:px-6 lg:px-8">
  <h1 class="text-2xl font-bold mb-4"><%= @image.name.humanize %></h1>
  <div class="flex flex-col items-center">
    <div class="m-5">
      <%= image_tag @image.display_image, class: "w-1/2 mx-auto" if @image.display_image.attached? %>
    </div>
    <p class="my-5 text-center">
      Category: <%= @image.category %>
    </p>
    <div class="m-5 p-3 border w-1/2 mx-auto">
      <p class="my-5">
        <% if @ai_enabled %>
         <%= generate_image_button(@image) unless @image.display_image.attached? %>
        <% else %>
          <%= content_tag(:div, content_tag(:p, "AI is disabled. Enable AI or upload image manually."), class: "p-2 shadow text-center") if !@image.display_image.attached? %>
        <% end %>
      </p>

      <p class="my-5">
        <%= @image.ai_prompt ? @image.ai_prompt : "No AI prompt available." %>
      </p>
      <div class="my-5">
        <p class="text-center"> Created: <%= time_ago_in_words @image.created_at %> ago</p>
        <p class="text-center"> Updated: <%= time_ago_in_words @image.updated_at %> ago</p>
      </div>
    </div>

    <div class="flex flex-col sm:flex-row sm:space-x-2 my-2">
      <%= purge_saved_images_button(@image) %>
            <%= describe_image_button(@image) %>

      <%= link_to "Edit", edit_image_path(@image), class: "text-white shadow rounded-lg py-2 px-4 bg-cyan-700 mb-2 sm:mb-0 font-medium text-center" %>
      <%= link_to "Crop", crop_image_path(@image), class: "text-white shadow rounded-lg py-2 px-4 bg-cyan-700 font-medium text-center" %>
    </div>
  </div>
</div>