config/routes.rb
Rails.application.routes.draw do
  resources :menus do
    resources :docs do
      member do
        get :enhance_image_description
      end
    end
  end
  patch "/ai", to: "application#ai", as: "ai"
  root to: "home#index"
  get "home/index"
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      patch "update_selection"
    end
  end
  resources :response_records do
    member do
      post "associate_response_image"
      post "remove_response_image"
    end
  end

  resources :images do
    post "find_or_create", on: :collection
    post "run_image_setup", on: :collection
    get "edit_multiple", on: :collection
    patch "update_multiple", on: :collection
    post "generate", on: :member
    get "crop", on: :member
    patch "croppable", on: :member
    post "purge_saved_images", on: :member
    post "describe", on: :member
  end
  resources :boards do
    member do
      patch "mark_as_favorite"
      patch "unfavorite"
      get "build"
      post "add_multiple_images"
      post "associate_image"
      post "remove_image"
      get "locked"
    end
  end
  resources :board_images do
    member do
      get "next"
      get "previous"
      patch "click"
    end
  end

  resources :response_boards, only: [:index, :show] do
    member do
      post "associate_response_image"
      post "remove_response_image"
    end
  end

  resources :response_images do
    member do
      get "next"
      get "previous"
      patch "click"
    end
  end

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/views/layouts/_alert.html.erb
    

    <% if alert.present? %>
      <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
    <% end %>
   

app/views/layouts/_current_selection.html.erb
<% if @current_user.current_user_selection %>
  <%= form_with(url: update_selection_user_path(@current_user), method: :patch, class: "mr-5 ml-5 mb-6", data: { controller: "selection-form", turbo_frame: "selection", turbo_action: "advance" }) do |form| %>
    <div class="flex space-x-3">
      <%= form.hidden_field :word_array, value: @current_user.current_user_selection&.words, data: { selection_form_target: "array" } %>
      <%= form.text_field :user_input, value: @current_user.current_word_list, placeholder: "Say something...", class: "w-2/3 sm:w-1/2 py-2 px-3 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none", data: { selection_form_target: "query", action: "input->selection-form#selection" } %>
      <% # Hiding situation field for now - WIP %>
      <%= form.text_field :situation, value: "#{@current_user.current_situation || ""}", placeholder: "Enter a situation", id: "situation", class: "situation w-1/4 sm:w-1/4 py-2 px-3 rounded border ring-0 focus:ring-4 focus:ring-orange-100 focus:shadow-none focus:border-orange-500 focus:outline-none hidden", data: { selection_form_target: "situation", action: "input->selection-form#selection" } %>
      <%= form.submit "Send", class: "px-3 py-2 font-medium bg-green-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-green-400 focus:ring-4 ring-0 focus:ring-green-100 mr-3", data: { action: "click->selection-form#send" } %>
      <%= form.submit "Clear", class: "px-3 py-2 font-medium bg-orange-300 text-neutal-900 rounded flex items-center cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0 focus:ring-orange-100 mr-3" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_enable_ai_button.html.erb
<div class="px-3 py-2 rounded"  data-controller="ai" data-ai-mode="<%= @ai_enabled %>" data-ai-enabled-global="<%= @ai_global %>">
  <input
    class="h-3.5 w-8 enabled:cursor-pointer rounded-md disabled:opacity-50 disabled:cursor-not-allowed"
    type="checkbox"
    role="switch"
    id="flexSwitchCheckDefault"
    data-ai-target="enable"
    data-action="click->ai#toggle"
    />
  <label
    class="inline-block pr-[0.15rem] text-xs text-white"
    for="flexSwitchCheckDefault"
    >Enable AI</label
  >
</div>

app/views/layouts/_errors.html.erb
<div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
  <h2><%= pluralize(model.errors.count, "error") %> prohibited this <%= model.class.to_s.downcase %> from being saved:</h2>

  <ul>
    <% model.errors.each do |error| %>
        <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>

app/views/layouts/_footer.html.erb
<footer class="text-center text-blue-600 mb-8">
    <p>&copy; 2023 SpeakEasy. All rights reserved.</p>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-800">
    <div class="flex items-center justify-between px-4 py-3 md:py-4 md:px-6">
        <a href="/" class="text-white font-semibold text-lg">
            SpeakEZ
        </a>
        <%= render "layouts/enable_ai_button" if user_signed_in? && current_user.admin? %>
        <div class="hidden md:flex items-center space-x-4 ml-4 md:ml-10">
            <% if user_signed_in? %>
            <%= current_user_first_favorite_board_button(current_user) %>
            <%= link_to "Menus", menus_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "My Boards", boards_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Responds Boards", response_boards_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" if current_user.admin? %>
            <%= link_to "Responds Records", response_records_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" if current_user.admin? %>
            <%= link_to "Users", users_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" if current_user.admin? %>
            <%= link_to "New Image", new_image_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

            <%= link_to "Image Library", images_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>

            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium", form_class: "inline-block" %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <%= link_to "Login", new_user_session_path, class: "text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
        </div>
        <button id="menu-btn" class="md:hidden">
            <svg class="h-6 w-6 text-gray-300 hover:text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7" />
            </svg>
        </button>
    </div>
    <!-- Mobile menu -->
    <div id="menu" class="hidden">
        <a href="#" class="block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white">About</a>
        <a href="#" class="block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white">Contact</a>
        <% if user_signed_in? %>
        <%= link_to "My Boards", boards_path, class: "block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <%= link_to "Images", images_path, class: "block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white", form_class: "inline-block" %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <%= link_to "Login", new_user_session_path, class: "block px-4 py-2 text-sm text-gray-300 hover:bg-gray-700 hover:text-white" %>
        <% end %>
  </div>
</nav>

app/views/layouts/_notice.html.erb
    

    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpeakEasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: "module" %>
    <script src="https://kit.fontawesome.com/7747fb4a3a.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg-stone-50">
    <%= render "layouts/navbar" %>
    <%= render "layouts/notice" %>
       <%= render "layouts/alert" %>
    <div class="justify-center p-2 md:p-4">
    <%= render "layouts/current_selection" if user_signed_in? && @ai_enabled && current_user.admin? && @show_toolbars %>
    <%= render "images/find_or_create" if user_signed_in? && @show_toolbars %>

      <%= yield %>

    </div>
    <script>
      // Simple JavaScript to toggle the mobile menu
      document.addEventListener('DOMContentLoaded', () => {
        const menuBtn = document.getElementById('menu-btn');
        const menu = document.getElementById('menu');

        menuBtn.addEventListener('click', () => {
          menu.classList.toggle('hidden');
        });
      });
    </script>

  </body>
</html>

app/views/layouts/play_mode.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpeakEasy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
       <%= javascript_include_tag "application", type: "module" %>
       <script src="https://kit.fontawesome.com/7747fb4a3a.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-teal-100 h-full">
    <div class="bg-gray-800 h-full">
      <div class="flex items-center justify-between px-4 py-3 md:py-4 md:px-6">
        <%= link_to @board do %>
          <h1 class="text-xl font-bold text-white p-2 outline rounded-lg">
            <%= icon("fa-solid", "arrow-left") %> <%= @board.name %>
          </h1>
        <% end %>
        <div class="text-xs text-white">  <%= @board.static? ? "STATIC MODE" : "BETA MODE" %></div>
      </div>
    </div>
    <div class="pt-3" data-controller="static-board">
      <div class="text-center">
        <ul class="flex justify-center text-4xl font-bold" id="the-list" data-static-board-target="list"></ul>

        <div class="mx-auto w-1/2 p-4 flex justify-around">
          <button class="bg-gray-100 rounded-lg py-3 px-5 font-medium" data-action="click->static-board#clearList">Clear</button>
          <button class="bg-green-100 rounded-lg py-3 px-5 font-medium" data-action="click->static-board#speakList">Speak</button>
        </div>

      </div>
      <div class="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4 m-3">

        <% @board_images.each do |board_image| %>
          <div id="<%= dom_id board_image %>" class="w-full" data-controller='static-image' data-static-image-label="<%= board_image.label.upcase %>" data-static-image-target="wrapper" data-action="click->static-image#speak">
            <div class="bg-white rounded-lg shadow overflow-hidden group cursor-pointer" data-action="click->speech#speak">
              <div class="relative w-full h-0 pb-[100%]"> <!-- Aspect Ratio Box -->
              <% if board_image.display_image.attached? %>
                <%= image_tag board_image.display_image, class: "absolute top-0 left-0 w-full h-full object-contain" %>
                <% else %>
                  <div class="absolute top-0 left-0 w-full h-full bg-gray-200 flex items-center justify-center text-gray-400 text-2xl font-bold"><%= board_image.label.upcase %></div>
                <% end %>
                <% if board_image.private %>
                  <span class="absolute top-2 right-2 bg-gray-900 bg-opacity-75 text-white text-xs px-1.5 py-0.5 rounded-full">Private</span>
                <% end %>
              </div>
              <div class="p-1">
                <p class="truncate text-gray-800 font-small hover:text-blue-600 text-center">
                  <%= board_image.label %>
                </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </body>
</html>